version: '3.1'
services:
  mongo: 
    image: mongo
    volumes:
      - './dump/:/docker-entrypoint-initdb.d'
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
  app:
    image: registry.redirectme.net/region/app:staging
    ports:
      - '3030:3000'
    environment:
      - MONGO_SERVER=mongo
  db:
    image: "registry.redirectme.net/postgres11:full"
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=ru_RU.utf8 --lc-collate=ru_RU.utf8 --lc-ctype=ru_RU.utf8
    ports:
      - "5434:5432"
    volumes:
      - "./pgdump:/docker-entrypoint-initdb.d"
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=q@q
      - PGADMIN_DEFAULT_PASSWORD=qwerty
